tasks:
  - init: echo "Replace me with a build script for the project."
    command: firebase login --no-localhost
image:
  file: .gitpod.Dockerfile


ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - eg2.vscode-npm-script